# Generated by Django 4.2.5 on 2023-10-27 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0006_quote_equip_value_alter_labor_create_ux_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labor',
            name='create_ux',
            field=models.PositiveBigIntegerField(default=1698433785),
        ),
        migrations.AlterField(
            model_name='quote',
            name='create_ux',
            field=models.PositiveBigIntegerField(default=1698433785),
        ),
    ]
