# Generated by Django 4.2.5 on 2023-11-02 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0039_initial'),
        ('quote', '0014_remove_labor_type_alter_labor_create_ux_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='labor',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.types'),
        ),
        migrations.AlterField(
            model_name='labor',
            name='create_ux',
            field=models.PositiveBigIntegerField(default=1698961005),
        ),
        migrations.AlterField(
            model_name='quote',
            name='create_ux',
            field=models.PositiveBigIntegerField(default=1698961005),
        ),
    ]
