# Generated by Django 4.2.5 on 2023-10-27 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='create_ux',
            field=models.PositiveBigIntegerField(default=1698427993),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.PositiveIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='zipcode',
            field=models.PositiveIntegerField(blank=True),
        ),
    ]
