# Generated by Django 4.2.5 on 2023-09-26 20:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0001_initial'),
        ('inventory', '0002_remove_inventory_attributes_remove_inventory_model_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attributes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Make',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('country', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='makes', to='home.country')),
            ],
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('manual_link', models.CharField(default='', max_length=200)),
                ('weight_g', models.IntegerField(default=0)),
                ('value', models.IntegerField(default=0)),
                ('create_ux', models.BigIntegerField(default=1695760650)),
                ('image', models.CharField(default='', max_length=100)),
                ('make', models.ManyToManyField(to='inventory.make')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='models', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Types',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('icon', models.CharField(default='', max_length=200)),
                ('makes', models.ManyToManyField(to='inventory.make')),
                ('model_list', models.ManyToManyField(to='inventory.model')),
            ],
        ),
        migrations.CreateModel(
            name='Subtypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('model_list', models.ManyToManyField(to='inventory.model')),
                ('types', models.ManyToManyField(to='inventory.types')),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('rate', models.IntegerField(default=0)),
                ('serial_number', models.CharField(max_length=100)),
                ('label', models.CharField(max_length=200)),
                ('purchase_price', models.IntegerField(default=0)),
                ('notes', models.CharField(max_length=1000)),
                ('create_ux', models.BigIntegerField(default=1695760650)),
                ('exists', models.BooleanField(default=True)),
                ('attributes', models.ManyToManyField(to='inventory.attributes')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventories', to='inventory.model')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='attributes',
            name='model_list',
            field=models.ManyToManyField(to='inventory.model'),
        ),
        migrations.AddField(
            model_name='attributes',
            name='subtypes',
            field=models.ManyToManyField(to='inventory.subtypes'),
        ),
        migrations.AddField(
            model_name='attributes',
            name='types',
            field=models.ManyToManyField(to='inventory.types'),
        ),
    ]
