# Generated by Django 4.2.5 on 2023-10-04 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='make',
            field=models.CharField(default='_', max_length=100),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='create_ux',
            field=models.BigIntegerField(default=1696446406),
        ),
        migrations.AlterField(
            model_name='unit',
            name='create_ux',
            field=models.BigIntegerField(default=1696446406),
        ),
    ]
