# Generated by Django 4.2.5 on 2023-10-06 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_alter_inventory_create_ux_alter_types_unit_list_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='create_ux',
            field=models.BigIntegerField(default=1696621529),
        ),
        migrations.AlterField(
            model_name='subtypes',
            name='unit_list',
            field=models.ManyToManyField(blank=True, related_name='subtypes', to='inventory.unit'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='create_ux',
            field=models.BigIntegerField(default=1696621529),
        ),
    ]
