# Generated by Django 4.2.5 on 2023-10-09 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_alter_inventory_create_ux_alter_subtypes_unit_list_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='create_ux',
            field=models.BigIntegerField(default=1696874496),
        ),
        migrations.AlterField(
            model_name='subtypes',
            name='types',
            field=models.ManyToManyField(blank=True, related_name='subtypes', to='inventory.types'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='create_ux',
            field=models.BigIntegerField(default=1696874496),
        ),
    ]
