# Generated by Django 4.2.5 on 2023-10-30 13:20

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0032_alter_inventory_create_ux_alter_inventory_label_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='create_ux',
            field=models.BigIntegerField(default=1698672021),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='serial_number',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, default=[], max_length=30), size=None),
        ),
        migrations.AlterField(
            model_name='unit',
            name='create_ux',
            field=models.BigIntegerField(default=1698672021),
        ),
    ]
