# Generated by Django 4.2.5 on 2023-11-02 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0014_remove_labor_type_alter_labor_create_ux_and_more'),
        ('inventory', '0037_attributes_makes_alter_inventory_create_ux_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attributes',
            name='attribute_class',
        ),
        migrations.RemoveField(
            model_name='attributes',
            name='makes',
        ),
        migrations.RemoveField(
            model_name='attributes',
            name='unit_list',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='attributes',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='make',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='user',
        ),
        migrations.RemoveField(
            model_name='make',
            name='country',
        ),
        migrations.RemoveField(
            model_name='subtypes',
            name='types',
        ),
        migrations.RemoveField(
            model_name='subtypes',
            name='unit_list',
        ),
        migrations.RemoveField(
            model_name='types',
            name='makes',
        ),
        migrations.RemoveField(
            model_name='types',
            name='unit_list',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='make',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='user',
        ),
        migrations.DeleteModel(
            name='Attributeclass',
        ),
        migrations.DeleteModel(
            name='Attributes',
        ),
        migrations.DeleteModel(
            name='Inventory',
        ),
        migrations.DeleteModel(
            name='Make',
        ),
        migrations.DeleteModel(
            name='Subtypes',
        ),
        migrations.DeleteModel(
            name='Types',
        ),
        migrations.DeleteModel(
            name='Unit',
        ),
    ]
