# Generated by Django 4.2.5 on 2023-10-27 17:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(default=1, max_length=100)),
                ('create_ux', models.PositiveBigIntegerField(default=1698428495)),
                ('modified_dt', models.DateField(auto_now=True)),
                ('paid', models.BooleanField(default=False)),
                ('total', models.PositiveIntegerField(default=0)),
                ('contents', models.JSONField(default=dict)),
                ('adds', models.JSONField(default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
