# Generated by Django 4.2.5 on 2023-11-02 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0011_alter_invoice_create_ux'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Invoice',
        ),
    ]
